services:
  - type: web
    name: media-downloader
    env: python
    buildCommand: |
      sudo apt-get update && sudo apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: starter
    rootDir: .
